name: Test

on:
  push:
    branches:
      - "**"
      - "!v**"
  pull_request:

jobs:
  build:
    name: Build
    permissions:
      contents: write
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14.2
        with:
          cmake-version: "3.21.x"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Configure CMake (ubuntu)
        if: contains(matrix.os, 'ubuntu')
        run: cmake -B build -S msdf-atlas-gen -G Ninja -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Configure CMake (macos)
        if: contains(matrix.os, 'macos')
        run: cmake -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_BUILD_TYPE=Release -B build -S msdf-atlas-gen -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Configure CMake (windows)
        if: contains(matrix.os, 'windows')
        run: cmake -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22000.0 -B build -S msdf-atlas-gen -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release --parallel 4

      - name: Build (TypeScript)
        run: npm run build

      - name: Rename
        run: node rename.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.os }}
          path: bin/*
          retention-days: 1

  deploy:
    name: Deploy
    permissions:
      contents: write
      packages: write
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Verify
        run: find . -type f
