name: Test

on:
  push:
    branches:
      - "**"
      - "!v**"
  pull_request:

jobs:
  build:
    name: Build
    permissions:
      contents: write
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.14.2
        with:
          cmake-version: "3.23.x"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        env:
          VCPKG_ROOT: ${{ github.workspace }}/vcpkg
        run: cmake -S msdf-atlas-gen -B build -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=build/bin

      - name: Rename
        run: node rename.js

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.os }}
          path: bin/*
          retention-days: 1

  deploy:
    name: Deploy
    permissions:
      contents: write
      packages: write
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Verify
        run: find . -type f
